[project]
name = "placeholder-html"
version = "0.1.0"
description = "Plain HTML Placeholder Website for People that need an Internet Presence "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
]
